apiVersion: v1
kind: Namespace
metadata:
  name: apple
  labels:
    name: apple
---
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  namespace: apple
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
  namespace: apple
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: apple
  ports:
    - port: 80
      targetPort: 5678 #